app/urls.py
from django.urls import path

from .views import HomeView

app_name = 'app'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

customer/urls.py
from django.urls import path

from .views import AddNewCustomer, CustomerList, CustomerDetails, EditCustomerDetailsView, \
    CustomerRecords, RecordView

app_name = 'customer'

urlpatterns = [
    path('add-new-customer/', AddNewCustomer.as_view(), name='add-customer'),
    path('list/', CustomerList.as_view(), name='customer-list'),
    path('list/<int:customer_id>/', CustomerDetails.as_view(), name='customer-details'),
    path('list/<int:customer_id>/edit/', EditCustomerDetailsView.as_view(), name='edit-customer'),
    path('customer-records/<int:customer_id>/', CustomerRecords.as_view(), name='customer-records'),
    path('records/<str:invoice_id>/', RecordView.as_view(), name='record-view'),
]

friab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('sales/', include('sales.urls')),
    path('customer/', include('customer.urls')),
    path('admin/', admin.site.urls),
]

fuzzy_octo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('sales/', include('sales.urls')),
    path('customer/', include('customer.urls')),
    path('admin/', admin.site.urls),
]

sales/urls.py
from django.urls import path

from .views import CreateInvoiceView, OrderDetailsView, GetCustomerLastBal, \
            TestView, SearchInvoiceView, UpdateInvoiceView, AddRandomBillView, \
            DeleteInvoiceItem

app_name = 'sales'

urlpatterns = [
    path('invoice/', CreateInvoiceView.as_view(), name='invoice'),
    path('search-invoice/', SearchInvoiceView.as_view(), name='search-invoice'),
    path('update-invoice/', UpdateInvoiceView.as_view(), name='update-invoice'),
    path('update-invoice/<str:invoice_id>/', UpdateInvoiceView.as_view(), name='fetch-invoice'),
    path('get-last-bal/<int:customer_id>', GetCustomerLastBal.as_view(), name='last-balance'),
    path('random-bill/', AddRandomBillView.as_view(), name='random-bill'),
    path('test/', TestView.as_view(), name='print-invoice'),
    path('order-info/', OrderDetailsView.as_view(), name='order-info'),
    path('delete-item/', DeleteInvoiceItem, name='delete-item')
]

customer/models.py
from django.db import models


class Customer(models.Model):

    name = models.CharField(max_length=255, null=True, blank=True)
    firm_name = models.CharField(max_length=255, null=True, blank=True)
    address = models.TextField(blank=True, null=True)
    gstin = models.CharField(max_length=15, null=True, blank=True)
    primary_num = models.BigIntegerField(null=True, blank=True)
    secondary_num = models.BigIntegerField(null=True,blank=True)
    category = models.CharField(max_length=16, default='Category General')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

customer/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateResponseMixin
from django.views import View
from django.conf import settings
from django.shortcuts import redirect
from django.db.models import Sum
from django.db.models import F

from .models import Customer
from sales.models import Invoice, Item
from helpers.helpers import pg_records
import locale


class AddNewCustomer(TemplateResponseMixin, View):
    template_name = 'customer/add_new_customer.html'

    def get(self, request):
        template_values = {
            'STATIC_URL': settings.STATIC_URL,
        }
        return self.render_to_response(template_values)

    def post(self, request):
        try:
            pri_number = int(self.request.POST['primary_num'])
        except ValueError:
            pri_number = 0
        try:
            sec_number = int(self.request.POST['secondary_num'])
        except ValueError:
            sec_number = 0

        c = Customer(
            name=str(self.request.POST['name']).upper(),
            firm_name=str(self.request.POST['firm_name']).upper(),
            address=str(self.request.POST['address']).upper(),
            gstin=str(self.request.POST['gstin']).upper(),
            primary_num=pri_number,
            secondary_num=sec_number,
            category=self.request.POST['category']
        )
        c.save()

        return render(request, 'customer/add_customer_success.html', {'STATIC_URL': settings.STATIC_URL})


class CustomerList(TemplateResponseMixin, View):
    template_name = 'customer/customer_list.html'

    def get(self, request):
        customers_obj = Customer.objects.order_by("firm_name").all()
        customers = pg_records(request, customers_obj, 10)
        return self.render_to_response({
            'STATIC_URL': settings.STATIC_URL,
            'customers': customers
        })


class CustomerDetails(TemplateResponseMixin, View):
    template_name = 'customer/customer_details.html'

    def get(self, request, customer_id):
        try:
            customer = Customer.objects.get(id=customer_id)
        except Customer.DoesNotExist:
            return render(request, 'app/404.html', {'STATIC_URL': settings.STATIC_URL})
        return self.render_to_response({
            'STATIC_URL': settings.STATIC_URL,
            'customer': customer
        })


class CustomerRecords(TemplateResponseMixin, View):
    template_name = "customer/customer_records.html"

    def get(self, request, customer_id):
        customer = Customer.objects.get(id=customer_id)

        invoice_obj = Invoice.objects.filter(customer_id=customer_id).order_by('-created_at')

        if not invoice_obj:
            invoice = pg_records(request, invoice_obj, 1)
            return self.render_to_response({
                'STATIC_URL': settings.STATIC_URL,
                'invoice': invoice,
                'customer': customer.firm_name,
                'total_sale': 0,
                'current_balance': 0,
                'joined': customer.created_at,
                'visits': 0,
            })

        invoice = pg_records(request, invoice_obj, 10)
        locale.setlocale(locale.LC_MONETARY, 'en_IN')

        total_sale = invoice_obj.exclude(sub_total=0)\
            .aggregate(total=Sum(F('sub_total') + F('p_and_f') + F('round_off')))['total']
        latest_record = invoice_obj.latest('created_at')
        visits = invoice_obj.exclude(sub_total=0).count()

        return self.render_to_response({
            'STATIC_URL': settings.STATIC_URL,
            'invoice': invoice,
            'customer': customer.firm_name,
            'total_sale': locale.currency(total_sale, grouping=True),
            'current_balance': locale.currency(latest_record.current_bal, grouping=True),
            'joined': customer.created_at,
            'visits': visits,
        })


class EditCustomerDetailsView(TemplateResponseMixin, View):
    template_name = "customer/edit_customer.html"

    def get(self, request, customer_id):
        try:
            customer = Customer.objects.get(id=customer_id)
        except Customer.DoesNotExist:
            return render(request, 'app/404.html', {'STATIC_URL': settings.STATIC_URL})
        return self.render_to_response({
            'STATIC_URL': settings.STATIC_URL,
            'customer': customer
        })

    def post(self, request, customer_id):
        try:
            pri_num = int(self.request.POST['primary_num'])
        except ValueError:
            pri_num = 0
        try:
           sec_num = int(self.request.POST['secondary_num'])
        except ValueError:
            sec_num = 0
        try:
            customer = Customer.objects.get(id=customer_id)
            customer.name = str(self.request.POST['name']).upper()
            customer.firm_name = str(self.request.POST['firm_name']).upper()
            customer.address = str(self.request.POST['address']).upper()
            customer.gstin = str(self.request.POST['gstin']).upper()
            customer.primary_num = pri_num
            customer.secondary_num = sec_num
            customer.category = self.request.POST['category']
            customer.save()
        except Customer.DoesNotExist:
            return render(request, 'app/404.html', {'STATIC_URL': settings.STATIC_URL})
        return redirect('customer:customer-details', customer_id)


class RecordView(TemplateResponseMixin, View):
    template_name = "customer/invoice_record.html"

    def get(self, request, invoice_id):
        invoice = Invoice.objects.get(id=invoice_id)

        return self.render_to_response({
            'STATIC_URL': settings.STATIC_URL,
            'title': invoice.customer_name,
            'invoice': invoice,
            'items': Item.objects.filter(invoice=invoice),
        })

customer/templates/customer/add_customer_success.html
{% extends 'app/base_site.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
<div class="row">
    <div class="col-md-10 text-center center-div">
        <div class="callout callout-success">
        <h4>Success!</h4>

        <p>Customer added successfully..</p>
            <a href="{% url 'customer:add-customer' %}">Click to add more customers.</a>
    </div>
    </div>
</div>
</div>
    <link rel="stylesheet" href="{% static css %}css/customer.css">
{% endblock %}

customer/templates/customer/add_new_customer.html
{% extends 'app/base_site.html' %}
{% load static %}
{% block content %}
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Customer
      </h1>
    </section>
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-8">
          <!-- general form elements -->
          <div class="box box-success">
            <div class="box-header with-border">
              <h3 class="box-title">Add a New Customer</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
              <form action="{% url 'customer:add-customer' %}" method="post" class="form-horizontal">
                {% csrf_token %}
                <div class="box-body">
                  <div class="form-group">
                    <label for="name" class="col-sm-3 control-label">Customer Name</label>

                    <div class="col-sm-9">
                      <input type="text" name="name" class="form-control" placeholder="Enter customer name...">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="firm" class="col-sm-3 control-label">Firm Name</label>

                    <div class="col-sm-9">
                      <input type="text" name="firm_name" class="form-control" placeholder="Enter name of the firm...">
                    </div>
                  </div>
                  <div class="form-group">
                      <label for="address" class="col-sm-3 control-label">Address</label>

                      <div class="col-sm-9">
                          <textarea class="form-control" name="address" placeholder="Enter full address of the shop..."></textarea>
                      </div>
                  </div>
                  <div class="form-group">
                      <label for="gstin" class="col-sm-3 control-label">GSTIN</label>

                      <div class="col-sm-9">
                        <input type="text" name="gstin" class="form-control" placeholder="Enter GSTIN of customer...">
                      </div>
                  </div>
                  <div class="form-group">
                      <label for="primary-num" class="col-sm-3 control-label">Primary Number</label>

                      <div class="col-sm-9">
                        <input type="number" name="primary_num" class="form-control" placeholder="Enter Primary Number...">
                      </div>
                  </div>
                  <div class="form-group">
                      <label for="secondary-num" class="col-sm-3 control-label">Secondary Number</label>

                      <div class="col-sm-9">
                        <input type="number" name="secondary_num" class="form-control" placeholder="Enter Secondary Number...">
                      </div>
                  </div>
                  <div class="form-group">
                      <label for="category" class="col-sm-3 control-label">Category</label>

                      <div class="col-sm-9">
                        <select name="category" class="form-control">
                            <option value="General Category">General Category</option>
                            <option value="A Category">A Category</option>
                            <option value="B Category">B Category</option>
                        </select>
                      </div>
                  </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer text-center">
                <button type="submit" class="btn btn-info">Save</button>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
        </div>
      </div>
    </section>
  </div>
    <script src="{% static j %}js/customer.js"></script>
{% endblock content %}

customer/templates/customer/customer_list.html
{% extends 'app/base_site.html' %}
{% load  static %}

{% block content %}
    <div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
        <div class="box">
        <div class="box-header">
          <h3 class="box-title">Customers List</h3>
        </div>
        <div class="box-body">
          <table id="example2" class="table table-bordered table-hover">
            <thead>
            <tr>
              <th>Firm Name</th>
              <th class="text-center">Name</th>
              <th class="text-center">Address</th>
              <th class="text-center">Phone Number</th>
              <th class="text-center" style="width: 136px;">#</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                  <td>{% if customer.firm_name == '' %}Unknown
                      {% else %} {{ customer.firm_name }}
                      {% endif %}
                  </td>
                  <td class="text-center">{% if customer.name == '' %}Unknown
                      {% else %} {{ customer.name }}
                      {% endif %}
                  </td>
                  <td class="text-center">{% if customer.address == '' %}Unknown
                      {% else %} {{ customer.address }}
                      {% endif %}
                  </td>
                  <td class="text-center">{% if customer.primary_num == 0 %}Unknown
                      {% else %} {{ customer.primary_num }}
                      {% endif %}
                  </td>
                  <td class="text-right"><a href="{% url 'customer:customer-details' customer.id %}" class="button btn btn-success">Info</a> / <a href="{% url 'customer:customer-records' customer.id %}" class="button btn btn-primary">View</a></td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="box-footer">
            <h4>
            {% if customers.has_previous %}
                <a href="?page={{ customers.previous_page_number }}">< Prev</a> |
            {% endif %}

            {% if customers.has_next %}
                <a href="?page={{ customers.next_page_number }}">Next ></a>
            {% endif %}

            <span>Page {{ customers.number }} of {{ customers.paginator.num_pages }}</span>
            </h4>
        </div>
        </div>

        </div>
        </div>
    </div>
    </div>
{% endblock %}

customer/templates/customer/customer_records.html
{% extends 'app/base_site.html' %}
{% load humanize %}

{% block content %}
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12">
            <div class="box">
            <div class="box-header">
                <h3 class="box-title">Transaction Details of <span style="margin-left: 4px;">{{ customer }}</span></h3>
            </div>
                <div class="content-header">
                    <div class="row">
                        <div class="col-lg-3 col-xs-6">
                          <!-- small box -->
                          <div class="small-box bg-aqua">
                            <div class="inner">
                              <h3>{{ total_sale }}</h3>

                              <p>Total Sale</p>
                            </div>
                            <div class="icon">
                              <i class="ion ion-social-usd"></i>
                            </div>
                          </div>
                        </div>
                        <!-- ./col -->
                        <div class="col-lg-3 col-xs-6">
                          <!-- small box -->
                          <div class="small-box bg-green">
                            <div class="inner">
                              <h3>{{joined|date:'M-yy'}}</h3>

                              <p>Journey Joined</p>
                            </div>
                            <div class="icon">
                              <i class="ion ion-ios-calendar"></i>
                            </div>
                          </div>
                        </div>
                        <!-- ./col -->
                        <div class="col-lg-3 col-xs-6">
                          <!-- small box -->
                          <div class="small-box bg-yellow">
                            <div class="inner">
                              <h3>{{ current_balance }}</h3>

                              <p>Current Balance</p>
                            </div>
                            <div class="icon">
                              <i class="ion ion-cash"></i>
                            </div>
                          </div>
                        </div>
                        <!-- ./col -->
                        <div class="col-lg-3 col-xs-6">
                          <!-- small box -->
                          <div class="small-box bg-red">
                            <div class="inner">
                              <h3>{{ visits }}</h3>

                              <p>Total Visits</p>
                            </div>
                            <div class="icon">
                              <i class="ion ion-android-walk"></i>
                            </div>
                          </div>
                        </div>
                        <!-- ./col -->
                      </div>
                </div>
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Date</th>
                  <th class="text-center">Sub Total</th>
                  <th class="text-center">Invoice Amount</th>
                  <th class="text-center">Amount Paid</th>
                  <th class="text-center">Current Balance</th>
                  <th class="text-center" style="width: 136px;">#</th>
                </tr>
                </thead>
                <tbody>
                {% for i in invoice %}
                    <tr>
                      <td>{{ i.date|date:"d-M-yy" }}</td>
                      <td class="text-center">{{ i.sub_total|intcomma }}</td>
                      <td class="text-center">{{ i.total_amount|intcomma }}</td>
                      <td class="text-center">{{ i.amount_paid|intcomma }}</td>
                      <td class="text-center">{{ i.current_bal|intcomma }} {% if i.current_bal < 0 %}(CR.){% else %}(DR.){% endif %}</td>
                      <td class="text-center"><a href="{% url 'customer:record-view' i.id %}" class="button btn btn-success">View</a></td>
                    </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
            <div class="box-footer">
                <h4>
                {% if invoice.has_previous %}
                    <a href="?page={{ invoice.previous_page_number }}">< Prev</a> |
                {% endif %}

                {% if invoice.has_next %}
                    <a href="?page={{ invoice.next_page_number }}">Next ></a>
                {% endif %}

                <span>Page {{ invoice.number }} of {{ invoice.paginator.num_pages }}</span>
                </h4>
            </div>
            </div>

            </div>
            </div>
        </div>
    </div>
{% endblock %}

customer/templates/customer/edit_customer.html
{% extends 'app/base_site.html' %}
{% load static %}
{% block content %}
    <div class="content-wrapper">
    <div class="content" style="height: 577px;">
        <div class="col-md-5 align-div-center">
          <!-- Horizontal Form -->
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Edit Customer Details</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form action="{% url 'customer:edit-customer' customer.id %}" method="POST" class="form-horizontal">
              <div class="box-body">
                  {% csrf_token %}
                <div class="form-group">
                  <label class="col-sm-3 control-label">Name</label>

                  <div class="col-sm-9">
                    <input type="text" name="name" value="{{ customer.name }}" class="form-control" placeholder="Customer Name">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Firm Name</label>

                  <div class="col-sm-9">
                    <input type="text" name="firm_name" value="{{ customer.firm_name }}" class="form-control" placeholder="Firm Name">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Address</label>

                  <div class="col-sm-9">
                    <input type="text" name="address" value="{{ customer.address }}" class="form-control" placeholder="Address">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">GST Number</label>

                  <div class="col-sm-9">
                    <input type="text" name="gstin" value="{{ customer.gstin }}" class="form-control" placeholder="GST Number">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Primary Number</label>

                  <div class="col-sm-9">
                    <input type="number" name="primary_num" value="{{ customer.primary_num }}" class="form-control" placeholder="Primary Number">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Secondary Number</label>

                  <div class="col-sm-9">
                    <input type="number" name="secondary_num" value="{{ customer.secondary_num }}" class="form-control" placeholder="Secondary Number">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Category</label>

                  <div class="col-sm-9">
                    <select name="category"  class="form-control">
                        <option value="{{ customer.category }}">{{ customer.category }}</option>
                        <option value="General Category">General Category</option>
                        <option value="A Category">A Category</option>
                        <option value="B Category">B Category</option>
                    </select>
                  </div>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <a href="{% url 'customer:customer-details' customer.id %}" class="btn btn-default" style="margin-left: 176px;">Cancel</a>
                <button type="submit" class="btn btn-info" style="width: 68px;">Save</button>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
        </div>
        </div>
    </div>
    </div>
    <link rel="stylesheet" href="{% static css%}css/customer.css">
{% endblock %}

customer/templates/customer/invoice_record.html
{% extends 'app/base_site.html' %}
{% block content %}
    <div class="content-wrapper invoice-body">

    <section class="content-header">
      <h1>
        Metro Motors Inc.
      </h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-success">
            <div class="box-header">
              <h1 class="box-title col-sm-2" style="margin-top: 7px;">Buyer Name</h1>
                <div class="col-sm-4">
                    <p class="header" style="margin-top: 7px; font-weight: bold">{{ invoice.customer_name }}</p>
                </div>
                <h1 class="box-title col-sm-1" style="margin-top: 7px;">Date</h1>
                <div class="col-sm-4">
                    <p class="header" style="margin-top: 7px; font-weight: bold">{{ invoice.date|date:"d-M-yy" }}</p>
                </div>
            </div>

          <div class="col-xs-12 box-header" id="customer_details">
              <h1 class="box-title col-sm-2" style="margin-top: 7px;">Address</h1>
              <div class="col-sm-4">
                  <p class="header" style="margin-top: 7px; font-weight: bold">{{ invoice.customer_address }}</p>
              </div>
              <h1 class="box-title col-sm-1" style="margin-top: 7px;">Phone</h1>
              <div class="col-sm-4">
                  <p class="header" style="margin-top: 7px; font-weight: bold">{{ invoice.phone }}</p>
              </div>
          </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th class="text-center" style='width:5px;'>#</th>
                  <th style='width:250px;'>Product</th>
                  <th style='width:20px;'>Price</th>
                  <th style='width:20px;'>Quantity</th>
                  <th style='width:20px;'>Discount Percentage </th>
                  <th class='text-center' style='width:40px;'>Total</th>
                </tr>
                </thead>
                <tbody>
                {% for i in items %}
                    <tr>
                        <td class="text-center">{{ forloop.counter }}</td>
                        <td>{{ i.item_name}} <span style="margin-left: 9px;">{{i.item_mrp}}/=</span></td>
                        <td>{{ i.item_sp }}</td>
                        <td>{{ i.item_quantity }}</td>
                        <td>{{ i.item_discount }}</td>
                        <td class="text-center">{{ i.item_total }}</td>
                    </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-6 pull-right">
          <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title"><b>Grand Total</b></h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-bordered">
                <tr>
                  <th>Sub Total</th>
                  <th class="text-center"><p>{{ invoice.sub_total }}</p></th>
                </tr>
                <tr>
                  <th>Last Balance</th>
                  <th class="text-center"><p>{{ invoice.last_bal}}</p></th>
                </tr>
                <tr>
                  <th>Packaging & Forwarding</th>
                    <th class="text-center"><p>{{ invoice.p_and_f }}</p></th>
                </tr>
                <tr>
                  <th>Round Off</th>
                    <th class="text-center"><p>{{ invoice.round_off }}</p></th>
                </tr>
                <tr>
                    <th>Total Amount</th>
                    <th class="text-center"><p>{{ invoice.total_amount }}</p></th>
                </tr>
                <tr>
                  <th>Amount Paid</th>
                  <th class="text-center"><p>{{ invoice.amount_paid }}</p></th>
                </tr>
                <tr>
                  <th>Current Balance</th>
                  <th class="text-center"><p>{{ invoice.current_bal }}</p></th>
                </tr>
              </table>
            </div>
          </div>
        </div>
    </div>
        <div class="text-center">
            <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-primary">Go Back</a>
            <a href="{% url 'sales:fetch-invoice' invoice.id %}" class="btn btn-success" style="width: 79px; margin-left: 20px;">Edit</a>
        </div>
    </section>
  </div>
{% endblock %}